version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:focal
    steps:
      - checkout
      - run:
          name: apt update
          command: sudo apt update
      - run:
          name: install clang
          command: sudo apt install -y clang clang-format
      - run:
          name: GCC tests
          command: runci/tests-gcc
      - run:
          name: CLANG tests
          command: runci/tests-clang
